CREATE TABLE CATEGORIA (
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO CATEGORIA (NOME) VALUES ('LAZER');
INSERT INTO CATEGORIA (NOME) VALUES ('ALIMENTAÇÃO');
INSERT INTO CATEGORIA (NOME) VALUES ('SUPERMERCADO');
INSERT INTO CATEGORIA (NOME) VALUES ('FARMACIA');
INSERT INTO CATEGORIA (NOME) VALUES ('OUTROS');