CREATE TABLE CATEGORIA (
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO CATEGORIA (NOME) VALUES ('BEBIDAS');
INSERT INTO CATEGORIA (NOME) VALUES ('PERECIVEIS');
INSERT INTO CATEGORIA (NOME) VALUES ('HIGIENE PESSOAL');
INSERT INTO CATEGORIA (NOME) VALUES ('FARMACIA');
INSERT INTO CATEGORIA (NOME) VALUES ('FRIOS');
